--                                                          COVID_19 ANALYSIS

CREATE DATABASE PROJECT;
USE PROJECT;
SELECT * FROM COVID_19;

-- STRUCTURE OF THE TABLE
DESCRIBE COVID_19;

-- DISPLAY THE TOTAL NUMBER OF RECORDS IN COVID-19 TABLE
SELECT COUNT(*)
FROM COVID_19;

-- TO SEE IF THERE ARE NO DUPLICATE ENTRIES IN COUNTRY COLUMN
SELECT COUNTRY,COUNT(*)
FROM COVID_19
GROUP BY COUNTRY 
HAVING COUNT(COUNTRY) > 1;

-- ASSIGN PRIMARY KEY CONSTRAINT TO COLUMN NAME COUNTRY
SELECT * FROM COVID_19
WHERE COUNTRY IS NULL;
ALTER TABLE COVID_19
ADD PRIMARY KEY(COUNTRY);

-- TO REPLACE MISSING VALUES WITH NULL
UPDATE COVID_19
SET WHO_REGION=NULL
WHERE (WHO_REGION)='';


-- TO LOOK AT ALL THE COUNTRIES WITH NO WHO_REGION
SELECT COUNTRY,CONTINENT,WHO_REGION
FROM COVID_19
WHERE WHO_REGION IS NULL;

-- DISPLAY THE NUMBER OF NULL VALUES IN WHO_REGION COLUMN
SELECT COUNT(*) 
FROM COVID_19
WHERE WHO_REGION IS NULL; 

-- FILLING THE NULL VALUES USING CASE STATEMENT
SELECT CONTINENT ,WHO_REGION
FROM COVID_19
GROUP BY CONTINENT,WHO_REGION;

UPDATE COVID_19
SET WHO_REGION = CASE
WHEN CONTINENT IN ('North America','South America') THEN 'Americas'
WHEN CONTINENT='Africa' THEN 'Africa'
END;


-- 1. LOOKING AT TOP 10 COUNTRIES WITH MOST NUMBER OF CASES
SELECT COUNTRY,TOTALCASES FROM COVID_19
ORDER BY TOTALCASES  DESC
LIMIT 10;


-- 2. LOOKING AT TOP 10 COUNTRIES WITH  MOST NUMBER OF DEATHS
SELECT COUNTRY,TOTALDEATHS FROM COVID_19
ORDER BY TOTALDEATHS DESC
LIMIT 10;


-- 3. LOOKING AT TOTAL NUMBER OF CASES AND DEATH IN ALL THE CONTINENTS (FROM MOST TO LEAST)
SELECT CONTINENT,SUM(TOTALCASES) AS TOTALCASE_CONTINENT,SUM(TOTALDEATHS) AS TOTALDEATHS_CONTINENT
FROM COVID_19
GROUP BY CONTINENT
ORDER BY TOTALCASE_CONTINENT DESC,TOTALDEATHS_CONTINENT DESC;


-- 4. LOOKING AT TOTAL CASES VS TOTAL DEATHS (MORTALITY RATE)
-- SHOWS LIKELYHOOD OF DYING IF YOU CONTACT COVID IN YOUR COUNTRY
SELECT COUNTRY,TOTALCASES,TOTALDEATHS,ROUND((TOTALDEATHS/TOTALCASES)*100,2) AS MORTALITY_RATE
FROM COVID_19
ORDER BY MORTALITY_RATE DESC;


-- 5. LOOKING AT TOTAL NUMBER OF DEATHS IN ALL THE CONTINENTS
-- SHOWS WHICH CONTINENT HAS MOST AND LEAST DEATHS
SELECT CONTINENT,SUM(TOTALDEATHS) AS TOTALDEATHS_CONTINENT
FROM COVID_19
GROUP BY CONTINENT
ORDER BY TOTALDEATHS_CONTINENT DESC;

 
-- 6. LOOKING AT INDIA COVID-19 REPORT
SELECT * FROM COVID_19
WHERE COUNTRY='INDIA';


-- 7. LOOKING AT COUNTRIES WITH  MOST CASES WITH RESPECT TO ITS POPULATION(HIGHEST INFECTION RATE)
-- SHOWS WHAT PERCENT OF POPULATION GOT COVID
SELECT COUNTRY,(TOTALCASES/POPULATION)*100 AS INFECTION_RATE
FROM COVID_19
ORDER BY INFECTION_RATE DESC
LIMIT 5;                         -- (QATAR HAS MOST NUMBER OF CASES WITH RESPECT TO ITS POPULATION OR WE CAN SAY THAT ALMOST 4% OF QATAR PUPULATION WAS AFFECTED BY COVID-19)


-- 8. LOOKING AT COUNTRIES WITH  LEAST CASES WITH RESPECT TO ITS POPULATION (LOWEST INFECTION RATE)
SELECT COUNTRY,(TOTALCASES/POPULATION)*100 AS INFECTION_RATE
FROM COVID_19
ORDER BY INFECTION_RATE 
LIMIT 5;                         -- ANGOLA HAS LEAST CASES WITH RESPECT TO ITS POPULATION(ONLY 0.0025% OF ANGOLAS POPULATION WAS AFFECTED)


-- 10.RECOVERY RATE (TOP AND BOTTOM 5)
SELECT COUNTRY,(SUM(TOTALRECOVERED)/SUM(TOTALCASES))*100 AS RECOVERY_RATE
FROM COVID_19
WHERE TOTALCASES > 10000
GROUP BY COUNTRY
ORDER BY RECOVERY_RATE DESC
LIMIT 5;

SELECT COUNTRY,(SUM(TOTALRECOVERED)/SUM(TOTALCASES))*100 AS RECOVERY_RATE
FROM COVID_19
WHERE TOTALCASES > 10000
GROUP BY COUNTRY
ORDER BY RECOVERY_RATE 
LIMIT 5;

-- 11. LOOKING AT INDIA'S MORTALITY ,INFECTION RATE,DEATH RATE AND RECOVERY RATE
SELECT COUNTRY,POPULATION,TOTALCASES,TOTALDEATHS,(TOTALDEATHS/TOTALCASES)*100 AS MORTALITY_RATE,(TOTALCASES/POPULATION)*100 AS INFECTION_RATE
FROM COVID_19
WHERE COUNTRY='INDIA';

SELECT COUNTRY,POPULATION,TOTALCASES,TOTALDEATHS,TOTALRECOVERED,(TOTALDEATHS/POPULATION)*100 AS DEATH_RATE,(TOTALRECOVERED/TOTALCASES)*100 AS RECOVERY_RATE
FROM COVID_19
WHERE COUNTRY='INDIA';


-- 12. SHOWING COUNTRIES IN ASIA AND EUROPE WITH HIGHEST AND LOWEST DEATH COUNT PER POPULATION 
-- DEATH RATE OF COUNTRIES IN ASIA AND EUROPE
SELECT COUNTRY,CONTINENT,POPULATION,TOTALDEATHS,(TOTALDEATHS/POPULATION)*100 AS DEATH_RATE
FROM COVID_19
WHERE CONTINENT IN ('ASIA','EUROPE')
ORDER BY DEATH_RATE DESC;

SELECT COUNTRY,CONTINENT,POPULATION,TOTALDEATHS,(TOTALDEATHS/POPULATION)*100 AS HIGHEST_DEATHCOUNT
FROM COVID_19
WHERE CONTINENT IN ('ASIA','EUROPE')
ORDER BY HIGHEST_DEATHCOUNT ;


-- 13. TO SHOW GLOBAL DEATH PERCENTAGE 
-- GLOBAL DEATH PERCENTAGE ==>3.4748
SELECT SUM(TOTALCASES)AS TOTAL_CASES,SUM(TOTALDEATHS) AS TOTAL_DEATHS,(SUM(TOTALDEATHS)/SUM(TOTALCASES))* 100 AS GLOBAL_DEATH_PERCEBTAGE
FROM COVID_19;


-- 14. TO SHOW INFECTED POPULATION PERCENTAGE GLOBALLY
-- 0.36 PERCENT OF GLOBAL POLATION WAS INFECTED BY COVID
SELECT SUM(POPULATION) AS GLOBAL_POP,SUM(TOTALCASES) AS TOTAL_GLOBALCASES,(SUM(TOTALCASES)/SUM(POPULATION))*100 AS GLOBAL_INFECTION_RATE
FROM COVID_19;


-- 15. HOW MANY DISTINCT WHO(WORLD HEALTH ORG.)REGIONS ARE THERE?
SELECT DISTINCT WHO_REGION
FROM COVID_19;
SELECT COUNT(DISTINCT WHO_REGION)
FROM COVID_19;


-- 16. LOOKING AT TOTAL CASES AND DEATHS IN SOUTH-EASTASIA REGION
SELECT WHO_REGION,SUM(TOTALCASES),SUM(TOTALDEATHS)
FROM COVID_19
WHERE WHO_REGION='SOUTH-EASTASIA'
GROUP BY WHO_REGION;


-- 17. TO LOOK AT ALL THE COUNTRIES WHCIH HAS MORE MORTALITY RATE THAT THE GLOBAL MORTALITY RATE
-- USING SUBQUERY
SELECT COUNTRY,TOTALCASES,TOTALDEATHS,(TOTALDEATHS/TOTALCASES)*100 AS MORTALITY_RATE
FROM COVID_19
WHERE (TOTALDEATHS/TOTALCASES)*100 >(SELECT (SUM(TOTALDEATHS)/SUM(TOTALCASES))* 100 FROM COVID_19);


-- 18.TO ADD A NEW COLUMN NAME MORTALITY_RATE STRENTH AS HIGH,MODERATE AND LOW ON THE BASIS OF 
-- MORTALITY RATE IS GREATER THAN 4 THEN HIGH
-- MORTALITY RATE IS BETWEEN 2 THAN 4 THEN MODERATE
-- MORTALITY RATE IS LESS THAN 2 THEN LOW
SELECT COUNTRY,
CASE
WHEN ((TOTALDEATHS/TOTALCASES)*100 > 3.80) THEN 'HIGH'
WHEN (TOTALDEATHS/TOTALCASES)*100 BETWEEN 2 AND 3.80 THEN 'MODERATE'
WHEN ((TOTALDEATHS/TOTALCASES)*100 < 2) THEN 'LOW'
END AS MORTALITY_RATE_STRENTH
FROM COVID_19;

ALTER TABLE COVID_19
ADD MORTALITY_RATE_STRENTH VARCHAR(40);

UPDATE COVID_19
SET MORTALITY_RATE_STRENTH = CASE
WHEN ((TOTALDEATHS/TOTALCASES)*100 > 3.80) THEN 'HIGH'
WHEN (TOTALDEATHS/TOTALCASES)*100 BETWEEN 2 AND 3.80 THEN 'MODERATE'
WHEN ((TOTALDEATHS/TOTALCASES)*100 < 2) THEN 'LOW'
END;


-- 19.FIND THE COUNTRY WITH 3RD HIGHEST NUMBER OF CASES
-- USING OFFSET
SELECT COUNTRY,TOTALCASES
FROM COVID_19
ORDER BY TOTALCASES DESC
LIMIT 1
OFFSET 2;


-- 20. TO LOOK AT HOW MUCH PERCENT OF THE POPULATION IS TESTED
SELECT COUNTRY,(TOTALTESTS/POPULATION)*100 AS TEST_PERCENTAGE
FROM COVID_19
WHERE POPULATION > 100000
ORDER BY TEST_PERCENTAGE ASC;


-- 21. AS MOST OF THE RECORDS IN COLUMN NEW CASES,NEW DEATHS AND NEW RECOVERED ARE MISSING WE CAN DELETE THOSE COLUMNS
ALTER TABLE COVID_19
DROP COLUMN NEWCASES,DROP COLUMN NEWDEATHS,DROP COLUMN NEWRECOVERED;


-- 22. TO LOOK AT COUNTRIES AND THEIR MORTALITY STRENGTH RATE WHICH STARTS WITH 'A' AND ENDS WITH 'A'
SELECT COUNTRY,MORTALITY_RATE_STRENTH 
FROM COVID_19
WHERE COUNTRY LIKE 'A%A';


-- 23.TO LOOK AT TOTAL NUMBER OF COUNTRIES IN DIFFERENT WHO REGIONS AND CONTINENTS
SELECT WHO_REGION,COUNT(COUNTRY)
FROM COVID_19
GROUP BY WHO_REGION;         -- EUROPE REGION HAS THE MOST NUMBER OF COUNTRIES

SELECT CONTINENT,COUNT(COUNTRY)
FROM COVID_19
GROUP BY CONTINENT;


-- 24.DISPLAY THE COUNTRY CONCATENATED WITH ITS CONTINENTS AND TOTAL NUMBER OF CASES > 100000
SELECT CONCAT(COUNTRY,' (',CONTINENT,')') AS COUNTRY_CONT,TOTALCASES
FROM COVID_19
WHERE TOTALCASES > 100000;


-- 25.DISPLAY ALL THE DATA FROM THE TABLE WHERE CONTINENT IS EUROPE ,TOTAL CASES BETWEEN 100000 AND 500000,AND MORTALITY_RATE_STRENTH IS HIGH
SELECT *
FROM COVID_19
WHERE CONTINENT='EUROPE' AND (TOTALCASES BETWEEN 100000 AND 500000) AND (MORTALITY_RATE_STRENTH ='HIGH');


-- 26.LOOKING AT THE HIGHEST,LOWEST AND AVERAGE OF TOTAL CASES OF ALL CONTINENTS
SELECT CONTINENT,MAX(TOTALCASES),MIN(TOTALCASES),AVG(TOTALCASES)
FROM COVID_19
GROUP BY CONTINENT;

-- 27. TO LOOK AT THE COUNTRIES AND TOTAL DEATHS WHERE WHO REGION IS AMERICAS AND MORTALITY STRENGTH IS HIGH
SELECT COUNTRY,TOTALDEATHS FROM COVID_19
WHERE WHO_REGION='AMERICAS'AND MORTALITY_RATE_STRENTH='HIGH';

-- 28. DISPLAY THE COUNTRY,CONTINENT AND A LOWER CASE CODE TO IT.THE CODE WILL BE COMPOSE OF FIRST 3 LETTERS OF COUNTRY 
-- AND LAST 3 LETTERS OF THE CONTINENT 
SELECT COUNTRY,CONTINENT,CONCAT(LOWER(LEFT(COUNTRY,3)),LOWER(RIGHT(CONTINENT,3)),'-COV-19') AS CODE
FROM COVID_19;









